name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      working-dir: ./ivaApp 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: iva
      - name: Checkout openFrameworks
        uses: actions/checkout@v2
        with:
          repository:  openframeworks/openFrameworks
          path: ofx
      - name: Checkout ofxCv addon
        uses: actions/checkout@v2
        with:
          repository:  kylemcdonald/ofxCv
          path: ofx/addons
      - name: Show dirs
        run: ls -la
      - name: Show addon dirs
        run: ls -la ./ofx/addons/
#    - name: configure
#      run: ./configure
#    - name: make
#      run: make
#      working-directory: ${{env.working-dir}}
#    - name: make check
#      run: make check
#    - name: make distcheck
#      run: make distcheck
