name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      working-dir: ./ivaApp 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#    - name: configure
#      run: ./configure
#    - name: make
#      run: make
#      working-directory: ${{env.working-dir}}
#    - name: make check
#      run: make check
#    - name: make distcheck
#      run: make distcheck
