name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      working-dir: ./ivaApp 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: iva
      - name: Checkout openFrameworks
        uses: actions/checkout@v2
        with:
          repository:  https://github.com/openframeworks/openFrameworks.git
          path: ofx
      - name: Show dirs
        run: ln -s
#    - name: configure
#      run: ./configure
#    - name: make
#      run: make
#      working-directory: ${{env.working-dir}}
#    - name: make check
#      run: make check
#    - name: make distcheck
#      run: make distcheck
